### Imports and utility functions

In [1]:
import numpy as np
import pandas as pd
import os
import math

import urllib.request
import urllib.parse
import re

#### General links
- [Advent of Code 2021](https://adventofcode.com/2021)
- [Peter Norvig's solutions to 2018 AofC](https://github.com/norvig/pytudes/blob/master/ipynb/Advent-2018.ipynbhttps://github.com/norvig/pytudes/blob/master/ipynb/Advent-2018.ipynb)

# [Day 1](https://adventofcode.com/2021/day/1)

In [2]:
txt_file = '/Users/ryanmcgranaghan/Documents/Google_Advent_of_Code_2021/day1_input.txt'
f = open(txt_file,"r")
txt_data = f.read().split('\n')#.remove('')
f.close()

int_data = [int(x) for x in txt_data]
# int_data

In [8]:
int_data

[122,
 129,
 116,
 122,
 135,
 148,
 151,
 158,
 161,
 179,
 197,
 198,
 187,
 210,
 211,
 206,
 207,
 210,
 211,
 216,
 222,
 224,
 222,
 234,
 237,
 238,
 239,
 245,
 276,
 262,
 268,
 266,
 293,
 291,
 293,
 296,
 298,
 291,
 292,
 295,
 297,
 298,
 297,
 300,
 297,
 309,
 315,
 319,
 320,
 319,
 323,
 338,
 349,
 351,
 352,
 354,
 348,
 366,
 365,
 388,
 385,
 379,
 381,
 385,
 391,
 392,
 405,
 407,
 415,
 427,
 433,
 436,
 439,
 444,
 450,
 449,
 453,
 457,
 459,
 460,
 467,
 471,
 474,
 473,
 477,
 487,
 489,
 498,
 512,
 516,
 507,
 526,
 544,
 560,
 570,
 569,
 580,
 590,
 591,
 593,
 596,
 597,
 598,
 604,
 599,
 608,
 603,
 616,
 649,
 636,
 649,
 648,
 653,
 654,
 655,
 656,
 664,
 666,
 669,
 663,
 661,
 682,
 681,
 685,
 693,
 701,
 727,
 706,
 704,
 705,
 706,
 711,
 716,
 711,
 721,
 728,
 724,
 734,
 733,
 737,
 736,
 742,
 743,
 742,
 744,
 745,
 749,
 750,
 760,
 767,
 787,
 788,
 787,
 789,
 785,
 798,
 796,
 797,
 798,
 800,
 807,
 817,
 829,
 828,
 830,
 831,
 863

In [14]:
range(1,len(int_data))

range(1, 2000)

In [17]:
ctr = 0
growth_list = ['N/A']
for c in range(1,len(int_data)):
    
#     print(int_data[c])
    if int_data[c]>int_data[c-1]:
        ctr +=1
        growth_list.append('increased')
#         print('    increased')
    elif int_data[c]<int_data[c-1]:
        growth_list.append('decreased')
#         print('    decreased')
    else:
        growth_list.append('no change')
print('the answer to day 1, part 1 is {}'.format(ctr))

the answer to day 1, part 1 is 1462


In [20]:
sum_data = [int_data[x]+int_data[x+1]+int_data[x+2] for x in range(len(int_data)-2)]


In [21]:
sum_data

[367,
 367,
 373,
 405,
 434,
 457,
 470,
 498,
 537,
 574,
 582,
 595,
 608,
 627,
 624,
 623,
 628,
 637,
 649,
 662,
 668,
 680,
 693,
 709,
 714,
 722,
 760,
 783,
 806,
 796,
 827,
 850,
 877,
 880,
 887,
 885,
 881,
 878,
 884,
 890,
 892,
 895,
 894,
 906,
 921,
 943,
 954,
 958,
 962,
 980,
 1010,
 1038,
 1052,
 1057,
 1054,
 1068,
 1079,
 1119,
 1138,
 1152,
 1145,
 1145,
 1157,
 1168,
 1188,
 1204,
 1227,
 1249,
 1275,
 1296,
 1308,
 1319,
 1333,
 1343,
 1352,
 1359,
 1369,
 1376,
 1386,
 1398,
 1412,
 1418,
 1424,
 1437,
 1453,
 1474,
 1499,
 1526,
 1535,
 1549,
 1577,
 1630,
 1674,
 1699,
 1719,
 1739,
 1761,
 1774,
 1780,
 1786,
 1791,
 1799,
 1801,
 1811,
 1810,
 1827,
 1868,
 1901,
 1934,
 1933,
 1950,
 1955,
 1962,
 1965,
 1975,
 1986,
 1999,
 1998,
 1993,
 2006,
 2024,
 2048,
 2059,
 2079,
 2121,
 2134,
 2137,
 2115,
 2115,
 2122,
 2133,
 2138,
 2148,
 2160,
 2173,
 2186,
 2191,
 2204,
 2206,
 2215,
 2221,
 2227,
 2229,
 2231,
 2238,
 2244,
 2259,
 2277,
 2314,
 2342,


In [22]:
ctr = 0
growth_list = ['N/A']
for c in range(1,len(sum_data)):
    
#     print(sum_data[c])
    if sum_data[c]>sum_data[c-1]:
        ctr +=1
        growth_list.append('increased')
#         print('    increased')
    elif sum_data[c]<sum_data[c-1]:
        growth_list.append('decreased')
#         print('    decreased')
    else:
        growth_list.append('no change')
print('the answer to day 1, part 2 is {}'.format(ctr))

the answer to day 1, part 2 is 1497


# [Day 2](https://adventofcode.com/2021/day/2)

In [26]:
txt_file = '/Users/ryanmcgranaghan/Documents/Google_Advent_of_Code_2021/day2_input.txt'
f = open(txt_file,"r")
txt_data = f.read().split('\n')#.remove('')
f.close()



In [2]:
txt_data

['forward 5', 'down 5', 'forward 8', 'up 3', 'down 8', 'forward 2']

In [11]:
ctr_horizontal = 0
ctr_depth = 0

for t in txt_data:
    tmp = t.split(' ')
    if (tmp[0] == 'forward'):
        ctr_horizontal += int(tmp[1])
    elif (tmp[0] == 'down'):
        ctr_depth += int(tmp[1])
    elif (tmp[0] == 'up'):
        ctr_depth -= int(tmp[1])

    
print('the answer to day 2 part 1 = {}'.format(ctr_horizontal*ctr_depth))

the answer to day 2 part 1 = 1936494


In [29]:
ctr_horizontal = 0
ctr_depth = 0
ctr_aim = 0


for t in txt_data:
    tmp = t.split(' ')
#     print(tmp)

    if (tmp[0] == 'forward'):
        ctr_horizontal += int(tmp[1])
        ctr_depth += ctr_aim*int(tmp[1])

    elif (tmp[0] == 'down'):
        ctr_aim += int(tmp[1])

    elif (tmp[0] == 'up'):
        ctr_aim -= int(tmp[1])
    

#     print('    horizontal = {}'.format(ctr_horizontal))
#     print('      tmp horizontal = {}'.format(tmp_horizontal))
#     print('    depth = {}'.format(ctr_depth))
#     print('    aim = {}'.format(ctr_aim))
#     print('      tmp aim = {}'.format(tmp_aim))
    
print('the answer to day 2 part 2 = {}'.format(ctr_horizontal*ctr_depth))

the answer to day 2 part 2 = 1997106066


# [Day 3](https://adventofcode.com/2021/day/3)

In [123]:
txt_file = '/Users/ryanmcgranaghan/Documents/Google_Advent_of_Code_2021/day3_input.txt'
f = open(txt_file,"r")
txt_data = f.read().split('\n')#.remove('')
f.close()

In [124]:
array_input = [] #np.empty(shape=(len(txt_data),5))
for t in txt_data:
#     print(t)
    tmp_array = [char for char in t]
#     print(tmp_array)
    array_input.append(tmp_array)


In [70]:
first_digit = [int(a[0]) for a in array_input]
second_digit = [int(a[1]) for a in array_input]
third_digit = [int(a[2]) for a in array_input]
fourth_digit = [int(a[3]) for a in array_input]
fifth_digit = [int(a[4]) for a in array_input]


In [109]:
def most_common(list_input):
    if list_input.count(0) > list_input.count(1):
        return 0
    if list_input.count(0) < list_input.count(1):
        return 1

def least_common(list_input):
    if list_input.count(0) > list_input.count(1):
        return 1
    if list_input.count(0) < list_input.count(1):
        return 0
    
# def binary2decimal(bin_number):
#     summer = 0
#     for i in range(len(bin_number)):
#         print(bin_number[i])
#         print(i)
# #         summer += bin_number[-(i+1)]*2**(len(bin_number)-i)
#         summer += bin_number[i]*(2**(i))
        
#     return summer

In [110]:
gamma_rate = []
epsilon_rate = []

for i in range(len(array_input[0])):
    digit = [int(a[i]) for a in array_input]
    gamma_rate.append(most_common(digit))
    epsilon_rate.append(least_common(digit))
print(gamma_rate)
print(epsilon_rate)

gamma_rate_decimal = int( "".join([str(g) for g in gamma_rate]),2 )
epsilon_rate_decimal = int( "".join([str(e) for e in epsilon_rate]),2 )
print('the answer to day 3 part 1 = {}'.format(gamma_rate_decimal*epsilon_rate_decimal))

[1, 0, 1, 1, 0]
[0, 1, 0, 0, 1]
the answer to day 3 part 1 = 198


In [125]:

existing_array = np.array(array_input)

for i in range(len(array_input[0])):
    digit = [int(a[i]) for a in existing_array]
    if digit.count(0) > digit.count(1):
        mcd = 0
    if digit.count(0) < digit.count(1):
        mcd = 1
    if digit.count(0) == digit.count(1):
        mcd = 1
    idx_tmp = np.nonzero(np.array(digit)==mcd)
    existing_array = existing_array[idx_tmp]
    print(len(existing_array))
    if len(existing_array) == 1:
        print(existing_array)
        ox_gen_rating = existing_array
ox_gen_rating_decimal = int( "".join([str(o) for o in ox_gen_rating[0]]),2 )
        
        
existing_array = np.array(array_input)
for i in range(len(array_input[0])):
    digit = [int(a[i]) for a in existing_array]
    if digit.count(0) > digit.count(1):
        mcd = 1
    if digit.count(0) < digit.count(1):
        mcd = 0
    if digit.count(0) == digit.count(1):
        mcd = 0
    idx_tmp = np.nonzero(np.array(digit)==mcd)
    existing_array = existing_array[idx_tmp]
    print(len(existing_array))
    if len(existing_array) == 1:
        print(existing_array)
        co2_scrub_rating = existing_array
co2_scrub_rating_decimal = int( "".join([str(o) for o in co2_scrub_rating[0]]),2 )

print('the answer to day 3 part 2 = {}'.format(ox_gen_rating_decimal*co2_scrub_rating_decimal))

506
262
137
74
40
26
16
10
5
3
2
1
[['0' '0' '0' '1' '1' '1' '1' '1' '1' '1' '0' '1']]
494
240
110
54
24
11
4
2
1
[['1' '0' '1' '0' '1' '0' '0' '0' '0' '1' '0' '1']]
0
0
0
the answer to day 3 part 2 = 1370737


# [Day 4](https://adventofcode.com/2021/day/4)

In [153]:
txt_file = '/Users/ryanmcgranaghan/Documents/Google_Advent_of_Code_2021/day4_input.txt'
f = open(txt_file,"r")
txt_data = f.read().split('\n')#.remove('')
f.close()

# int_data = [int(x) for x in txt_data]
# int_data

In [154]:
input_nums = txt_data[0]
input_nums = [int(i) for i in input_nums.split(',')]
txt_data = txt_data[1:]

In [155]:
txt_data

['',
 '85 23 65 78 93',
 '27 53 10 12 26',
 ' 5 34 83 25  6',
 '56 40 73 29 54',
 '33 68 41 32 82',
 '',
 ' 8 31 14 70 91',
 '53 49 86 13 21',
 '66 28 76 78 93',
 '39 63 80 43 23',
 '56 25 60 67 72',
 '',
 '67 78 36 64 14',
 '46 16 80 23 94',
 '22 47 51 65 57',
 '33 76 21 92 97',
 '31 95 54 27 20',
 '',
 ' 1 77 86 43 30',
 '28 88  7  5 60',
 '66 24  3 57 33',
 '38 23 59 84 44',
 '74 47 17 29 85',
 '',
 '21 50 86  2 70',
 '85 19 22 93 25',
 '99 38 74 30 65',
 '81  0 47 78 63',
 '34 11 51 88 64',
 '',
 '45 15 29 81 30',
 '75 21 88 91 49',
 '39 20  4 17 78',
 '10 12 38 11  7',
 '98  6 65 69 86',
 '',
 '36 20 31 44 69',
 '30 65 55 88 64',
 '74 85 82 61  5',
 '57 17 90 43 54',
 '58 83 52 23  7',
 '',
 '42 16 82 86 76',
 '60 26 27 59 55',
 ' 7 53 22 78  5',
 '18 61 10 15 17',
 '28 46 14 87 77',
 '',
 '21 43 15 47 61',
 '24 76 28  3 27',
 '19 62 69 82 93',
 '49 29 97 74 41',
 '92 36 37 99 40',
 '',
 '31  4  3 62 51',
 '24 57 78 67 53',
 '13  5 76 38 55',
 '79  9 75 98 71',
 '65  1 39 18 47',


In [156]:
board_number = 0
list_boards = []
for t in range(0,len(txt_data),6):
    print('empty')#txt_data[t])
    array_tmp = np.zeros( (5,5) )
    for r in range(5):
        print('   {}'.format(txt_data[t+r]))
        array_tmp[r,:] = txt_data[t+1+r].split()
    list_boards.append(array_tmp)


empty
   
   85 23 65 78 93
   27 53 10 12 26
    5 34 83 25  6
   56 40 73 29 54
empty
   
    8 31 14 70 91
   53 49 86 13 21
   66 28 76 78 93
   39 63 80 43 23
empty
   
   67 78 36 64 14
   46 16 80 23 94
   22 47 51 65 57
   33 76 21 92 97
empty
   
    1 77 86 43 30
   28 88  7  5 60
   66 24  3 57 33
   38 23 59 84 44
empty
   
   21 50 86  2 70
   85 19 22 93 25
   99 38 74 30 65
   81  0 47 78 63
empty
   
   45 15 29 81 30
   75 21 88 91 49
   39 20  4 17 78
   10 12 38 11  7
empty
   
   36 20 31 44 69
   30 65 55 88 64
   74 85 82 61  5
   57 17 90 43 54
empty
   
   42 16 82 86 76
   60 26 27 59 55
    7 53 22 78  5
   18 61 10 15 17
empty
   
   21 43 15 47 61
   24 76 28  3 27
   19 62 69 82 93
   49 29 97 74 41
empty
   
   31  4  3 62 51
   24 57 78 67 53
   13  5 76 38 55
   79  9 75 98 71
empty
   
   59  4 38 95 99
   85 68 69 93 43
   83 57 48 42 15
   47 50 80 79 90
empty
   
   21 37 14 67 95
   88 39 26 38 49
   89 83 54 77 96
   48 86 94 19 20
empty
   
    1 

In [157]:
np.shape(list_boards)

(100, 5, 5)

In [158]:
list_boards_stack = np.stack(list_boards)

In [159]:
def calc_winning_score(array,input_num):
    array = array.astype("float")
    array[np.where(array == 999.)] = np.nan
    sum_array = np.nansum(array)
    score = sum_array * input_num
    return score

In [160]:
check_boards = np.copy(list_boards_stack)
flag_stop = 0
for num in input_nums:
    print('checking input number = {}'.format(num))
    idx_loop = np.where(list_boards_stack == num)
    check_boards[idx_loop] = 999
    for c in range(len(list_boards_stack)):
        for c2 in range(len(list_boards_stack[c])):
            if (check_boards[c][c2,:] == 999.).all():
                print('Found winning board! = {}'.format(c))
                score = calc_winning_score(check_boards[c],num)
                print('the answer to day 4 part 1 = {}'.format(score))
                flag_stop = 1
                break
            elif (check_boards[c][:,c2] == 999.).all():
                print('Found winning board! = {}'.format(c))
                score = calc_winning_score(check_boards[c],num)
                print('the answer to day 4 part 1 = {}'.format(score))
                flag_stop = 1
                break
            else:
                continue
    if flag_stop == 1:
        break

checking input number = 1
checking input number = 76
checking input number = 38
checking input number = 96
checking input number = 62
checking input number = 41
checking input number = 27
checking input number = 33
checking input number = 4
checking input number = 2
checking input number = 94
checking input number = 15
checking input number = 89
checking input number = 25
checking input number = 66
checking input number = 14
checking input number = 30
checking input number = 0
checking input number = 71
checking input number = 21
checking input number = 48
checking input number = 44
checking input number = 87
checking input number = 73
checking input number = 60
checking input number = 50
checking input number = 77
checking input number = 45
checking input number = 29
checking input number = 18
checking input number = 5
Found winning board! = 36
the answer to day 4 part 1 = 5685.0


In [176]:
check_boards = np.copy(list_boards_stack)

winning_boards = []
flag_stop = 0 

for num in input_nums:
    print('checking input number = {}'.format(num))
    idx_loop = np.where(list_boards_stack == num)
    check_boards[idx_loop] = 999
    for c in range(len(list_boards_stack)):
        for c2 in range(len(list_boards_stack[c])):
            if (check_boards[c][c2,:] == 999.).all():
                winning_boards.append(c)
                if len(set(winning_boards)) == np.shape(list_boards_stack)[0]:
                    print('found last board to win = {}'.format(c))
                    score = calc_winning_score(check_boards[c],num)
                    print('the answer to day 4 part 2 = {}'.format(score))
                    flag_stop = 1
                    break
                break
            elif (check_boards[c][:,c2] == 999.).all():
                winning_boards.append(c)
                if len(set(winning_boards)) == np.shape(list_boards_stack)[0]:
                    print('found last board to win = {}'.format(c))
                    score = calc_winning_score(check_boards[c],num)
                    print('the answer to day 4 part 2 = {}'.format(score))
                    flag_stop = 1
                    break
                break
            else:
                continue
    if flag_stop == 1:
        break

checking input number = 1
checking input number = 76
checking input number = 38
checking input number = 96
checking input number = 62
checking input number = 41
checking input number = 27
checking input number = 33
checking input number = 4
checking input number = 2
checking input number = 94
checking input number = 15
checking input number = 89
checking input number = 25
checking input number = 66
checking input number = 14
checking input number = 30
checking input number = 0
checking input number = 71
checking input number = 21
checking input number = 48
checking input number = 44
checking input number = 87
checking input number = 73
checking input number = 60
checking input number = 50
checking input number = 77
checking input number = 45
checking input number = 29
checking input number = 18
checking input number = 5
checking input number = 99
checking input number = 65
checking input number = 16
checking input number = 93
checking input number = 95
checking input number = 37
checki

In [108]:
chc2[0][0,:]

array([  0.,   0., 999.,   0.,   0.])

In [109]:
(chc2[0][1,:] == 0.).all()

True

In [112]:
for c in range(len(chc2)):
    for c2 in range(len(chc2[c])):
        if (chc2[c][c2,:] == 1.).all():
            print('Found winning board! = {}'.format(c))
        elif (chc2[c][:,c2] == 1.).all():
            print('Found winning board! = {}'.format(c))
        else:
            continue
    

board is not yet a winner
board is not yet a winner
board is not yet a winner
board is not yet a winner
board is not yet a winner
board is not yet a winner
board is not yet a winner
board is not yet a winner
board is not yet a winner
board is not yet a winner
board is not yet a winner
board is not yet a winner
board is not yet a winner
board is not yet a winner
board is not yet a winner


# [Day 5](https://adventofcode.com/2021/day/5)

In [206]:
txt_file = '/Users/ryanmcgranaghan/Documents/Google_Advent_of_Code_2021/day5_input.txt'
f = open(txt_file,"r")
txt_data = f.read().split('\n')#.remove('')
f.close()

# int_data = [int(x) for x in txt_data]
# int_data

In [207]:
txt_data

['217,490 -> 217,764',
 '44,270 -> 373,599',
 '440,139 -> 440,303',
 '161,663 -> 345,663',
 '848,963 -> 908,963',
 '299,207 -> 162,70',
 '77,346 -> 77,686',
 '693,743 -> 693,127',
 '96,459 -> 96,779',
 '864,39 -> 233,670',
 '58,79 -> 203,79',
 '158,596 -> 463,291',
 '633,293 -> 136,293',
 '656,474 -> 656,72',
 '148,754 -> 947,754',
 '535,780 -> 535,460',
 '821,701 -> 821,796',
 '592,200 -> 592,610',
 '620,786 -> 722,786',
 '632,731 -> 536,731',
 '825,640 -> 195,10',
 '956,547 -> 956,387',
 '25,32 -> 981,988',
 '870,613 -> 870,16',
 '369,780 -> 369,362',
 '348,924 -> 243,924',
 '28,114 -> 540,114',
 '702,690 -> 702,335',
 '836,442 -> 184,442',
 '602,11 -> 602,651',
 '76,988 -> 608,988',
 '15,922 -> 951,922',
 '363,18 -> 296,18',
 '130,580 -> 516,580',
 '799,335 -> 858,335',
 '571,842 -> 571,800',
 '684,654 -> 684,971',
 '815,674 -> 66,674',
 '575,612 -> 575,919',
 '652,126 -> 822,296',
 '391,493 -> 730,493',
 '810,479 -> 810,807',
 '397,420 -> 780,37',
 '187,740 -> 869,740',
 '175,626 -

In [208]:
x1,y1,x2,y2 = map(list,zip(*[re.split(r",|->", t) for t in txt_data]))
x1 = [int(x) for x in x1]
x2 = [int(x) for x in x2]
y1 = [int(y) for y in y1]
y2 = [int(y) for y in y2]


In [80]:
# Create playing board
# board = np.zeros( (10,10) )
board = np.zeros( (1000,1000) )
# print(board)
# print('\n-------\n')
for pt in range(len(x1)):
#     print('working on point = {},{} -> {},{}'.format(x1[pt],y1[pt],x2[pt],y2[pt]))
    if (x1[pt] == x2[pt]) | (y1[pt] == y2[pt]):
        if (x1[pt] == x2[pt]):
            lowy = min(y1[pt],y2[pt])
            highy = max(y1[pt],y2[pt])
#             board[lowy:highy+1][x1[pt]] += 1
            for ys in range(lowy,highy+1):
                    board[ys][x1[pt]] += 1
        if (y1[pt] == y2[pt]):
            lowx = min(x1[pt],x2[pt])
            highx = max(x1[pt],x2[pt])
            board[y1[pt]][lowx:highx+1] += 1
#             [board[xval][y1[pt]]+=1 for xval in x1[pt]:x2[pt]]
#     print(board)
#     print('\n-------\n')

print('the answer to day 5 part 1 = {}'.format((board>=2).sum()))

the answer to day 5 part 1 = 6841


In [209]:
def angle_between(p1, p2):
    ang1 = np.arctan2(*p1[::-1])
    ang2 = np.arctan2(*p2[::-1])
    return np.rad2deg((ang1 - ang2) % (2 * np.pi))

In [215]:
def connect(x1,x2,y1,y2):
    ends = np.array(
        [
            [x1,y1],
            [x2,y2]
        ],dtype=int);
#     print(ends)    
    d0, d1 = np.abs(np.diff(ends, axis=0))[0]
    if d0 > d1: 
        return np.c_[np.linspace(ends[0, 0], ends[1, 0], d0+1, dtype=np.int32),
                     np.round(np.linspace(ends[0, 1], ends[1, 1], d0+1))
                     .astype(np.int32)]
    else:
        return np.c_[np.round(np.linspace(ends[0, 0], ends[1, 0], d1+1))
                     .astype(np.int32),
                     np.linspace(ends[0, 1], ends[1, 1], d1+1, dtype=np.int32)]


In [216]:
# Create playing board
# board = np.zeros( (10,10) )
board = np.zeros( (1000,1000) )
print(board)
print('\n-------\n')
for pt in range(len(x1)):
#     print('working on point = {},{} -> {},{}'.format(x1[pt],y1[pt],x2[pt],y2[pt]))
    pt1 = np.array((x1[pt],y1[pt]))
    pt2 = np.array((x2[pt],y2[pt]))
    ptdiff = pt2 - pt1
    if (x1[pt] == x2[pt]) | (y1[pt] == y2[pt]):
#         print('straight line')
        if (x1[pt] == x2[pt]):
            lowy = min(y1[pt],y2[pt])
            highy = max(y1[pt],y2[pt])
#             board[lowy:highy+1][x1[pt]] += 1
            for ys in range(lowy,highy+1):
                    board[ys][x1[pt]] += 1
        if (y1[pt] == y2[pt]):
            lowx = min(x1[pt],x2[pt])
            highx = max(x1[pt],x2[pt])
            board[y1[pt]][lowx:highx+1] += 1
#             [board[xval][y1[pt]]+=1 for xval in x1[pt]:x2[pt]]
    elif (np.mod( np.rad2deg( math.atan2(ptdiff[1],ptdiff[0]) ),45 ) == 0):# & (np.rad2deg( math.atan2(ptdiff[1],ptdiff[0]) ) != 0):
#         lowx = min(x1[pt],x2[pt])
#         highx = max(x1[pt],x2[pt])
#         lowy = min(y1[pt],y2[pt])
#         highy = max(y1[pt],y2[pt])
#         print('45 degree line')
#         lowx = x1[pt]
#         highx = x2[pt]
#         if lowx > highx:
#             xdir = -1
# #             lowx += 1
#         else:
#             xdir = 1
# #             highx += 1
#         lowy = y1[pt]
#         highy = y2[pt]
#         if lowy > highy:
#             ydir = -1
#             lowy -= 1
#         else:
#             ydir = 1
#             highy += 1
#         print('-------> x: {}-{} and y: {}-{}'.format(lowx,highx,lowy,highy))
#         for pts in list(zip(range(lowy,highy,ydir),range(lowx,highx,xdir))):
#             print('-------> pt = {}'.format(pts))
#             board[pts[0]][pts[1]] += 1
            
        pts_45 = connect(x1[pt],x2[pt],y1[pt],y2[pt])
        for pts in pts_45:
#             print('-------> pt = {}'.format(pts))
            board[pts[1]][pts[0]] += 1
            

#     print(board)
#     print('\n-------\n')

print('the answer to day 5 part 2 = {}'.format((board>=2).sum()))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

-------

the answer to day 5 part 2 = 19258


# [Day 6](https://adventofcode.com/2021/day/6)

In [51]:
txt_file = '/Users/ryanmcgranaghan/Documents/Google_Advent_of_Code_2021/day6_input_practice.txt'
f = open(txt_file,"r")
txt_data = f.read().split(',')#.remove('')
f.close()

int_data = [int(x) for x in txt_data]
# int_data

In [52]:
fish_list = int_data


In [53]:
num_days = 80
for dy in range(num_days):
    print('working on day = {}'.format(dy))
#     if (fish_list == 0).any():
#         fish_list[fish_list == 0] = 6
#         fish_list.append(8)
    ctr_add = 0
    for f in range(len(fish_list)):
        if (fish_list[f] == 0):
            fish_list[f] = 6
            ctr_add += 1
        else:
            fish_list[f] = fish_list[f] - 1
    if ctr_add > 0:
        fish_list = fish_list + list(np.repeat(8,ctr_add))
#     print('fish list after day {} = {}'.format(dy,fish_list))
print('the answer to day 6 part 1 = {}'.format(len(fish_list)))

working on day = 0
working on day = 1
working on day = 2
working on day = 3
working on day = 4
working on day = 5
working on day = 6
working on day = 7
working on day = 8
working on day = 9
working on day = 10
working on day = 11
working on day = 12
working on day = 13
working on day = 14
working on day = 15
working on day = 16
working on day = 17
working on day = 18
working on day = 19
working on day = 20
working on day = 21
working on day = 22
working on day = 23
working on day = 24
working on day = 25
working on day = 26
working on day = 27
working on day = 28
working on day = 29
working on day = 30
working on day = 31
working on day = 32
working on day = 33
working on day = 34
working on day = 35
working on day = 36
working on day = 37
working on day = 38
working on day = 39
working on day = 40
working on day = 41
working on day = 42
working on day = 43
working on day = 44
working on day = 45
working on day = 46
working on day = 47
working on day = 48
working on day = 49
working on

KeyboardInterrupt: 

In [99]:
from itertools import islice, cycle


def shift_dict(dct, shift):
    shift %= len(dct)
#     print('shift = {}'.format(shift))
    return OrderedDict(
        (k, v)
        for k, v in zip(dct.keys(), islice(cycle(dct.values()), shift, None))
    )

9

In [128]:
with open('day6_input.txt') as f:
    numbers = list(map(int, f.readline().strip().split(',')))

    fish_dict = {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0}
    print(fish_dict)
    list_dict = dict(Counter(numbers))
    print(list_dict)

    for fishes in list_dict:
        fish_dict[fishes] = list_dict[fishes]

    print(fish_dict)
    
    list_count = [i for i in fish_dict.values()]
    
    for i in range(256):
#         print(list_count)
        g=list_count[0]
        list_count.pop(0)
        list_count.append(g)
        if i > 0:
            list_count[6] += g
        
#         for t in range(len(list_count)-1):
# #             if t == len(list_count):
#             list_count[t] = list_count[t+1]
#         if i > 0:
#             list_count[6] += list_count[0]
#             list_count[8] = list_count[0] 
                
#             if i > 0:

#         print(list_count)
    print('the answer to day 6 part 2 = {}'.format(sum(list_count)))

#     for day in range(256):

#         zeros = fish_dict[0]
#         fish_dict = dict(shift_dict(fish_dict, 1))
#         fish_dict[6] = fish_dict[6] + zeros
# #         print('fish_dict  = {}'.format(fish_dict.values()))
#     print('the answer to day 6 part 2 = {}'.format(sum(fish_dict.values())))


{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0}
{3: 45, 5: 64, 1: 99, 2: 51, 4: 41}
{0: 0, 1: 99, 2: 51, 3: 45, 4: 41, 5: 64, 6: 0, 7: 0, 8: 0}
the answer to day 6 part 2 = 1609058859115


# [Day 7](https://adventofcode.com/2021/day/7)